### ISSUE TITLE
Data validation check - Correct data file format

### ISSUE THREAD

**Issue by mdahewlett** [UBC-MDS/DSCI522-2425-39-FMJ#28]

**Comment by jasonmlee** [comment]
The notes refer to this [link](https://microsoft.github.io/code-with-engineering-playbook/machine-learning/testing-data-science-and-mlops-code/
)

Doesn't look like we will need to check for "correct data file format" in our project as we are retrieving the data directly from the UCI repo. 

![CleanShot 2024-11-29 at 11 28 33](https://github.com/user-attachments/assets/d821bf8d-bcba-4a4a-ace1-59e373380d40)
