### ISSUE TITLE
Data validation check - Correct column names

### ISSUE THREAD

**Issue by mdahewlett** [UBC-MDS/DSCI522-2425-39-FMJ#29]

**Comment by jasonmlee** [comment]
Added the `strict=True` argument in the schema. The schema will now return an error if additional columns are found in the DataFrame. This helps to check for the correct column names.

Example error:
pandera.errors.SchemaError: additional column(s) ['name'] found in DataFrame

![CleanShot 2024-11-29 at 11 38 17](https://github.com/user-attachments/assets/70246496-3931-446f-8fe7-5bcbb6226c72)
