### ISSUE TITLE
Data validation check - Correct data types in each column

### ISSUE THREAD

**Issue by mdahewlett** [UBC-MDS/DSCI522-2425-39-FMJ#32]

**Comment by mdahewlett** [comment]
Initially I set different columns to int rather than float - like SEQN, age in years, diabetic status, etc - but looking at the errors caught in data validation, some obs from those cols were marked as float, even when inspecting the obs they were whole numbers, so I changed the int to float in the schema

**Comment by Forsythia-olive** [comment]
That makes sense.   Thanks Micheal
