### ISSUE TITLE
Data validation check - No outlier or anomalous values

### ISSUE THREAD

**Issue by mdahewlett** [UBC-MDS/DSCI522-2425-39-FMJ#34]

**Comment by mdahewlett** [comment]
Don't know what units blood glucose, blood insulin, and oral health levels are measured in the data, so did not add value ranges for those in the checks.

**Comment by Forsythia-olive** [comment]
That is okay. You need to do for all features. Daniel said we need to just make sure all the checks have been implemented on at least a feature.
