### ISSUE TITLE
Data validation check - Correct category levels (i.e., no string mismatches or single values)

### ISSUE THREAD

**Issue by mdahewlett** [UBC-MDS/DSCI522-2425-39-FMJ#35]

**Comment by jasonmlee** [comment]
Correct category levels are defined using `pa.check` for:

- age_group
- RIAGENDR
- PAQ605
- DIQ010

Invalid observations are removed after validation is conducted.

![CleanShot 2024-11-29 at 12 04 05](https://github.com/user-attachments/assets/130da476-9a39-4cfc-a272-bd29e5e5cc34)
