### ISSUE TITLE
Data validation check - Target/response variable follows expected distribution

### ISSUE THREAD

**Issue by mdahewlett** [UBC-MDS/DSCI522-2425-39-FMJ#36]

**Comment by jasonmlee** [comment]
I have revised "Table 3: Target column" to display `value_counts` to show the expected distribution between the Adult and Senior classes. I think it is a better representation compared to displaying the entire column.

![CleanShot 2024-11-29 at 12 11 31](https://github.com/user-attachments/assets/5623608b-572d-4b21-850b-5f890e20593c)
