### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by jasonmlee** [UBC-MDS/DSCI522-2425-39-FMJ#55]
- I've gone through the final checks and milestone 2 looks good to me. I'm able to run deepchecks in the docker container (thanks Forgive). You should be good to make the release. Thanks!

Things I've changed:
- Added some developer notes in the README file
- Removed redundant import statement in the deepchecks section of the notebook

**Comment by Forsythia-olive** [comment]
I have created the release
