### ISSUE TITLE
MS3:2 - EDA section - decide how to display the summary stats table

### ISSUE THREAD

**Issue by mdahewlett** [UBC-MDS/DSCI522-2425-39-FMJ#69]
Currently the table does not display nicely

**Comment by jasonmlee** [comment]
I added rounding to 2 decimal places and the quarto preview now looks like this. 

![CleanShot 2024-12-07 at 08 47 35@2x](https://github.com/user-attachments/assets/4c7f26ab-6999-4143-8937-e71342d3ae46)
